import {mkdir, readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCRIPT_ROOT = path.resolve(__dirname, '..');

const CWD = process.cwd();

function getArg(flag) {
  const idx = process.argv.indexOf(flag);
  return idx !== -1 ? process.argv[idx + 1] : null;
}

const TOKENS_PATH = path.join(SCRIPT_ROOT, 'theme-tokens.json');
const outArg = getArg('--out');
const GLOBAL_CSS_PATH = outArg
  ? path.resolve(CWD, outArg)
  : path.join(CWD, 'global.css');
const GENERATED_TS_PATH = path.join(CWD, 'src', 'theme', 'semanticColors.generated.ts');

const CHECK_MODE = process.argv.includes('--check');

function isHexColor(value) {
  return /^#[0-9A-Fa-f]{6}$/.test(value);
}

function validateTokens(tokens) {
  if (!tokens || typeof tokens !== 'object') {
    throw new Error('theme-tokens.json must export an object');
  }

  const {light, dark} = tokens;
  if (!light || !dark) {
    throw new Error('theme-tokens.json must include both "light" and "dark"');
  }

  const lightKeys = Object.keys(light);
  const darkKeys = Object.keys(dark);

  if (lightKeys.length === 0) {
    throw new Error('theme-tokens.json light theme cannot be empty');
  }

  const missingInDark = lightKeys.filter(k => !darkKeys.includes(k));
  const missingInLight = darkKeys.filter(k => !lightKeys.includes(k));

  if (missingInDark.length > 0 || missingInLight.length > 0) {
    throw new Error(
      [
        missingInDark.length > 0
          ? `Keys missing in dark: ${missingInDark.join(', ')}`
          : null,
        missingInLight.length > 0
          ? `Keys missing in light: ${missingInLight.join(', ')}`
          : null,
      ]
        .filter(Boolean)
        .join(' | '),
    );
  }

  for (const mode of ['light', 'dark']) {
    for (const [token, value] of Object.entries(tokens[mode])) {
      if (typeof value !== 'string' || !isHexColor(value)) {
        throw new Error(
          `Invalid color for ${mode}.${token}: ${String(value)} (expected #RRGGBB)`,
        );
      }
    }
  }
}

function buildCssBlock(selector, palette) {
  const lines = Object.entries(palette).map(
    ([token, value]) => `  --color-${token}: ${value};`,
  );

  return [selector + ' {', ...lines, '}'].join('\n');
}

function buildGlobalCss(tokens) {
  return [
    '@tailwind base;',
    '@tailwind components;',
    '@tailwind utilities;',
    '',
    '/* AUTO-GENERATED by scripts/generate-theme.mjs from theme-tokens.json. */',
    '/* Do not edit this file directly. */',
    '',
    buildCssBlock(':root', tokens.light),
    '',
    buildCssBlock('.dark:root', tokens.dark),
    '',
  ].join('\n');
}

function buildGeneratedTs(tokens) {
  return [
    '/* AUTO-GENERATED by scripts/generate-theme.mjs from theme-tokens.json. */',
    '/* Do not edit this file directly. */',
    '',
    `export const SEMANTIC_COLORS = ${JSON.stringify(tokens, null, 2)} as const;`,
    '',
    'export type ThemeMode = keyof typeof SEMANTIC_COLORS;',
    'export type SemanticColorToken = keyof typeof SEMANTIC_COLORS.light;',
    '',
    'export function getSemanticColor(',
    '  theme: ThemeMode,',
    '  token: SemanticColorToken,',
    '): string {',
    '  return SEMANTIC_COLORS[theme][token];',
    '}',
    '',
  ].join('\n');
}

async function writeOrCheck(filePath, nextContent) {
  let previous = '';
  try {
    previous = await readFile(filePath, 'utf8');
  } catch {
    previous = '';
  }

  if (CHECK_MODE) {
    if (previous !== nextContent) {
      throw new Error(
        `Generated file out of date: ${path.relative(CWD, filePath)}`,
      );
    }
    return;
  }

  if (previous !== nextContent) {
    await writeFile(filePath, nextContent, 'utf8');
    console.log(`updated ${path.relative(CWD, filePath)}`);
  } else {
    console.log(`unchanged ${path.relative(CWD, filePath)}`);
  }
}

async function main() {
  const raw = await readFile(TOKENS_PATH, 'utf8');
  const tokens = JSON.parse(raw);

  validateTokens(tokens);

  const globalCss = buildGlobalCss(tokens);
  const generatedTs = buildGeneratedTs(tokens);

  await mkdir(path.dirname(GENERATED_TS_PATH), {recursive: true});

  await writeOrCheck(GLOBAL_CSS_PATH, globalCss);
  await writeOrCheck(GENERATED_TS_PATH, generatedTs);
}

main().catch(err => {
  console.error(err.message);
  process.exit(1);
});
